name: BCA_exp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.3.4
  - notebook=6.4.6
  - scikit-learn=1.0.1
  - tensorflow=2.6.0
  - pymongo=3.12.0
  - pip=21.2.4
  - matplotlib=3.5.1
  - keras=2.6.0
  - seaborn=0.11.2
  - openpyxl=3.0.9
  - pip:
    - sacred==0.8.2
